CREATE TABLE NORTHWIND.CATEGORIES (CATEGORY_ID NUMERIC (22),
                        CATEGORY_NAME VARCHAR (15),
                        DESCRIPTION VARCHAR (2000),
                        PICTURE VARCHAR (255))
CREATE TABLE NORTHWIND.CUSTOMERS (CUSTOMER_ID NUMERIC (22),
                        CUSTOMER_CODE VARCHAR (5),
                        COMPANY_NAME VARCHAR (40),
                        CONTACT_NAME VARCHAR (30),
                        CONTACT_TITLE VARCHAR (30),
                        ADDRESS VARCHAR (60),
                        CITY VARCHAR (15),
                        REGION VARCHAR (15),
                        POSTAL_CODE VARCHAR (10),
                        COUNTRY VARCHAR (15),
                        PHONE VARCHAR (24),
                        FAX VARCHAR (24))
CREATE TABLE NORTHWIND.EMPLOYEES (EMPLOYEE_ID NUMERIC (22),
                        LASTNAME VARCHAR (20),
                        FIRSTNAME VARCHAR (10),
                        TITLE VARCHAR (30),
                        TITLE_OF_COURTESY VARCHAR (25),
                        BIRTHDATE DATE,
                        HIREDATE DATE,
                        ADDRESS VARCHAR (60),
                        CITY VARCHAR (15),
                        REGION VARCHAR (15),
                        POSTAL_CODE VARCHAR (10),
                        COUNTRY VARCHAR (15),
                        HOME_PHONE VARCHAR (24),
                        EXTENSION VARCHAR (4),
                        PHOTO VARCHAR (255),
                        NOTES VARCHAR (2000),
                        REPORTS_TO NUMERIC (22))
CREATE TABLE NORTHWIND.ORDER_DETAILS (ORDER_ID NUMERIC (22),
                        PRODUCT_ID NUMERIC (22),
                        UNIT_PRICE NUMERIC (22),
                        QUANTITY NUMERIC (22),
                        DISCOUNT NUMERIC (22))
CREATE TABLE NORTHWIND.ORDERS (ORDER_ID NUMERIC (22),
                        CUSTOMER_ID NUMERIC (22),
                        EMPLOYEE_ID NUMERIC (22),
                        ORDER_DATE DATE,
                        REQUIRED_DATE DATE,
                        SHIPPED_DATE DATE,
                        SHIP_VIA NUMERIC (22),
                        FREIGHT NUMERIC (22),
                        SHIP_NAME VARCHAR (40),
                        SHIP_ADDRESS VARCHAR (60),
                        SHIP_CITY VARCHAR (15),
                        SHIP_REGION VARCHAR (15),
                        SHIP_POSTAL_CODE VARCHAR (10),
                        SHIP_COUNTRY VARCHAR (15))
CREATE TABLE NORTHWIND.PRODUCTS (PRODUCT_ID NUMERIC (22),
                        PRODUCT_NAME VARCHAR (40),
                        SUPPLIER_ID NUMERIC (22),
                        CATEGORY_ID NUMERIC (22),
                        QUANTITY_PER_UNIT VARCHAR (20),
                        UNIT_PRICE NUMERIC (22),
                        UNITS_IN_STOCK NUMERIC (22),
                        UNITS_ON_ORDER NUMERIC (22),
                        REORDER_LEVEL NUMERIC (22),
                        DISCONTINUED CHAR (1))
CREATE TABLE NORTHWIND.SHIPPERS (SHIPPER_ID NUMERIC (22),
                        COMPANY_NAME VARCHAR (40),
                        PHONE VARCHAR (24))
CREATE TABLE NORTHWIND.SUPPLIERS (SUPPLIER_ID NUMERIC (22),
                        COMPANY_NAME VARCHAR (40),
                        CONTACT_NAME VARCHAR (30),
                        CONTACT_TITLE VARCHAR (30),
                        ADDRESS VARCHAR (60),
                        CITY VARCHAR (15),
                        REGION VARCHAR (15),
                        POSTAL_CODE VARCHAR (10),
                        COUNTRY VARCHAR (15))